final int mcVersion = project.mcVersion
final boolean unobfuscated = mcVersion >= 26_00_00

apply plugin: 'java-library'
apply plugin: 'maven-publish'
apply plugin: unobfuscated ? 'net.fabricmc.fabric-loom' : 'net.fabricmc.fabric-loom-remap'
apply plugin: 'com.replaymod.preprocess'

repositories {
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	if (!unobfuscated) {
		mappings "net.fabricmc:yarn:${project.minecraft_version}+build.${project.yarn_build}:v2"
		modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
		modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	} else {
		implementation "net.fabricmc:fabric-loader:${project.loader_version}"
		implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	}
}

JavaVersion JAVA_COMPATIBILITY = mcVersion >= 26_00_00 ? JavaVersion.VERSION_25 : JavaVersion.VERSION_21

loom {
	runConfigs.configureEach {
		runDir '../../run'
	}
	runConfigs.client {
		ideConfigGenerated = true
	}
}

String fullModVersion = project.mod_version
String fullProjectVersion = 'v' + project.mod_version + '-mc' + project.minecraft_version

group = project.maven_group
base.archivesName = project.archives_base_name
version = fullProjectVersion

processResources {
	def modProperties = [
		"id"                  : project.mod_id,
		"name"                : project.mod_name,
		"version"             : fullModVersion,
		"minecraft_dependency": project.minecraft_dependency,
	]
	inputs.properties(modProperties)

	filesMatching("fabric.mod.json") {
		expand modProperties
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = "UTF-8"
}

java {
	sourceCompatibility = JAVA_COMPATIBILITY
	targetCompatibility = JAVA_COMPATIBILITY
	withSourcesJar()
}

jar {
	inputs.property "archives_base_name", project.archives_base_name
	from("../../LICENSE") {
		rename { "${it}_${inputs.properties.archives_base_name}" }
	}
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
			artifactId = base.archivesName.get()
			version = fullProjectVersion
		}
	}
	repositories {
	}
}
