# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# JDK 25 路径
org.gradle.java.home=C:/Program Files/Java/jdk-25.0.3

# IntelliJ IDEA is not yet fully compatible with configuration cache
org.gradle.configuration-cache=false


# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=io.github.cbtc_59.voidquit
archives_base_name=voidquit-mc26.1.x

# Dependencies
fabric_api_version=0.145.4+26.1.2
